### ISSUE TITLE
Install problems on Windows 11

### ISSUE THREAD

**Issue by wbruninx** [marclelijveld/External-Tools-Model-Documentation#62]
I run the setup as administrator and it completes without any error, however tool is not showing up, no additional log files available. Clearly tried to install the latest version available for download eg v2.1.0

Checking different locations, being:

Program Files (x86), this is the location where the executable of the Model Documenter will be located. After installation you will find it in _C:\Program Files (x86)\Data-Marc\ModelDocumenter  ==> OK !

The external tools directory, To run an External tool from the Power BI Desktop ribbon, the pbitool.json integration file is mandatory. Therefore a file will be added to C:\Program Files (x86)\Common Files\microsoft shared\Power BI Desktop\ExternalTools  ==> NOK! Power BI Destop\External Tools does not exists.

Template file, the template to show the model documentation in a Power BI Report is also saved on your local machine. This file is saved at C:\Program Files (x86)\Common Files\Data-Marc\ModelDocumenter. In case you prefer to enhance or customize the template report, this is also the location where you need to place the file with the exact same name. ==> No Template

**Comment by wbruninx** [comment]
Creating the folder entries and copying the files myself I can launch ModelDocumenter from the External Tools Menu with errors : c:\Power BI Model Documenter\ModelDocumenter.vpax ==> Does NOT exists...

command window entries below : 

---
--- ModelDocumenter 2.1 for.Net (v4.0.30319)
---
Successfully loaded plugin CommandLineArgumentsParser, Version=3.0.23.0, Culture=neutral, PublicKeyToken=2990a79b704d8378 from assembly CommandLineArgumentsParser.dll
Successfully loaded plugin Dax.Metadata, Version=1.0.0.0, Culture=neutral, PublicKeyToken=aefcc2fb6c470ebf from assembly Dax.Metadata.dll
Successfully loaded plugin Dax.Model.Extractor, Version=1.0.0.0, Culture=neutral, PublicKeyToken=aefcc2fb6c470ebf from assembly Dax.Model.Extractor.dll
Successfully loaded plugin Dax.ViewVpaExport, Version=1.0.0.0, Culture=neutral, PublicKeyToken=aefcc2fb6c470ebf from assembly Dax.ViewVpaExport.dll
Successfully loaded plugin Dax.Vpax, Version=1.0.0.0, Culture=neutral, PublicKeyToken=aefcc2fb6c470ebf from assembly Dax.Vpax.dll
Successfully loaded plugin Microsoft.AnalysisServices.AdomdClient, Version=19.51.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91 from assembly Microsoft.AnalysisServices.AdomdClient.dll
Successfully loaded plugin Microsoft.AnalysisServices.Core, Version=19.51.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91 from assembly Microsoft.AnalysisServices.Core.dll
Successfully loaded plugin Microsoft.AnalysisServices, Version=19.51.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91 from assembly Microsoft.AnalysisServices.dll
Successfully loaded plugin Microsoft.AnalysisServices.SPClient.Interfaces, Version=19.51.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91 from assembly Microsoft.AnalysisServices.SPClient.Interfaces.dll
Successfully loaded plugin Microsoft.AnalysisServices.Tabular, Version=19.51.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91 from assembly Microsoft.AnalysisServices.Tabular.dll
Successfully loaded plugin Microsoft.AnalysisServices.Tabular.Json, Version=19.51.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91 from assembly Microsoft.AnalysisServices.Tabular.Json.dll
Successfully loaded plugin Microsoft.Identity.Client, Version=4.43.0.0, Culture=neutral, PublicKeyToken=0a613f4dd989e8ae from assembly Microsoft.Identity.Client.dll
Successfully loaded plugin Newtonsoft.Json, Version=13.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed from assembly Newtonsoft.Json.dll
Successfully loaded plugin System.Data.OleDb, Version=6.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51 from assembly System.Data.OleDb.dll
Successfully loaded plugin System.IO.Packaging, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a from assembly System.IO.Packaging.dll
Successfully loaded plugin System.Net.Http, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a from assembly System.Net.Http.dll
Successfully loaded plugin System.Net.Http.WebRequest, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a from assembly System.Net.Http.WebRequest.dll
Parsing results:
        Command line:
--server localhost:56591 --database 89787d9b-e38d-4e41-ac2c-b773bf92096a --filename c:\Power BI Model Documenter\ModelDocumenter.vpax --pbitemplate C:\Program Files (x86)\Common Files\Data-Marc\ModelDocumenter\ModelDocumentationTemplate_v2.1.0.pbit

        Parsed Arguments:
Argument: s(server), type: String, value: localhost:56591 (converted from: localhost:56591)
Argument: d(database), type: String, value: 89787d9b-e38d-4e41-ac2c-b773bf92096a (converted from: 89787d9b-e38d-4e41-ac2c-b773bf92096a)
Argument: f(filename), type: String, value: c:\Power BI Model Documenter\ModelDocumenter.vpax (converted from: c:\Power BI Model Documenter\ModelDocumenter.vpax)
Argument: p(pbitemplate), type: String, value: C:\Program Files (x86)\Common Files\Data-Marc\ModelDocumenter\ModelDocumentationTemplate_v2.1.0.pbit (converted from: C:\Program Files (x86)\Common Files\Data-Marc\ModelDocumenter\ModelDocumentationTemplate_v2.1.0.pbit)

        Arguments not specified:

        Additional arguments:



Unhandled Exception: System.ComponentModel.Win32Exception: The system cannot find the file specified
   at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start(String fileName)
   at ModelDocumenter.Program.Main(String[] args)

**Comment by wbruninx** [comment]
Creating the folder entries and copying the files manually I can launch now from External Tools menu with errors in the command window : 

---
--- ModelDocumenter 2.1 for.Net (v4.0.30319)
---
Successfully loaded plugin CommandLineArgumentsParser, Version=3.0.23.0, Culture=neutral, PublicKeyToken=2990a79b704d8378 from assembly CommandLineArgumentsParser.dll
Successfully loaded plugin Dax.Metadata, Version=1.0.0.0, Culture=neutral, PublicKeyToken=aefcc2fb6c470ebf from assembly Dax.Metadata.dll
Successfully loaded plugin Dax.Model.Extractor, Version=1.0.0.0, Culture=neutral, PublicKeyToken=aefcc2fb6c470ebf from assembly Dax.Model.Extractor.dll
Successfully loaded plugin Dax.ViewVpaExport, Version=1.0.0.0, Culture=neutral, PublicKeyToken=aefcc2fb6c470ebf from assembly Dax.ViewVpaExport.dll
Successfully loaded plugin Dax.Vpax, Version=1.0.0.0, Culture=neutral, PublicKeyToken=aefcc2fb6c470ebf from assembly Dax.Vpax.dll
Successfully loaded plugin Microsoft.AnalysisServices.AdomdClient, Version=19.51.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91 from assembly Microsoft.AnalysisServices.AdomdClient.dll
Successfully loaded plugin Microsoft.AnalysisServices.Core, Version=19.51.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91 from assembly Microsoft.AnalysisServices.Core.dll
Successfully loaded plugin Microsoft.AnalysisServices, Version=19.51.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91 from assembly Microsoft.AnalysisServices.dll
Successfully loaded plugin Microsoft.AnalysisServices.SPClient.Interfaces, Version=19.51.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91 from assembly Microsoft.AnalysisServices.SPClient.Interfaces.dll
Successfully loaded plugin Microsoft.AnalysisServices.Tabular, Version=19.51.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91 from assembly Microsoft.AnalysisServices.Tabular.dll
Successfully loaded plugin Microsoft.AnalysisServices.Tabular.Json, Version=19.51.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91 from assembly Microsoft.AnalysisServices.Tabular.Json.dll
Successfully loaded plugin Microsoft.Identity.Client, Version=4.43.0.0, Culture=neutral, PublicKeyToken=0a613f4dd989e8ae from assembly Microsoft.Identity.Client.dll
Successfully loaded plugin Newtonsoft.Json, Version=13.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed from assembly Newtonsoft.Json.dll
Successfully loaded plugin System.Data.OleDb, Version=6.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51 from assembly System.Data.OleDb.dll
Successfully loaded plugin System.IO.Packaging, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a from assembly System.IO.Packaging.dll
Successfully loaded plugin System.Net.Http, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a from assembly System.Net.Http.dll
Successfully loaded plugin System.Net.Http.WebRequest, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a from assembly System.Net.Http.WebRequest.dll
Parsing results:
        Command line:
--server localhost:57140 --database b16e70c9-a4ea-4ad9-ae30-a40acd72f45a --filename c:\Power BI Model Documenter\ModelDocumenter.vpax --pbitemplate C:\Program Files (x86)\Common Files\Data-Marc\ModelDocumenter\ModelDocumentationTemplate_v2.1.0.pbit

        Parsed Arguments:
Argument: s(server), type: String, value: localhost:57140 (converted from: localhost:57140)
Argument: d(database), type: String, value: b16e70c9-a4ea-4ad9-ae30-a40acd72f45a (converted from: b16e70c9-a4ea-4ad9-ae30-a40acd72f45a)
Argument: f(filename), type: String, value: c:\Power BI Model Documenter\ModelDocumenter.vpax (converted from: c:\Power BI Model Documenter\ModelDocumenter.vpax)
Argument: p(pbitemplate), type: String, value: C:\Program Files (x86)\Common Files\Data-Marc\ModelDocumenter\ModelDocumentationTemplate_v2.1.0.pbit (converted from: C:\Program Files (x86)\Common Files\Data-Marc\ModelDocumenter\ModelDocumentationTemplate_v2.1.0.pbit)

        Arguments not specified:

        Additional arguments:



Unhandled Exception: System.ComponentModel.Win32Exception: The system cannot find the file specified
   at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start(String fileName)
   at ModelDocumenter.Program.Main(String[] args)

**Comment by wbruninx** [comment]
log file & *.vpax created in C:\Power BI Model Documenter
ModelDocumenter.log file content:

10:24:48 AM Wednesday, October 9, 2024  :Exporting...
10:24:48 AM Wednesday, October 9, 2024  :[INFO] Get Dax.Model object from the SSAS engine
10:24:50 AM Wednesday, October 9, 2024  :[INFO] Get TOM model from the SSAS engine
10:24:50 AM Wednesday, October 9, 2024  :[INFO] Create VertiPaq Analyzer views
10:24:50 AM Wednesday, October 9, 2024  :[INFO] Exporting VPAX file
10:24:51 AM Wednesday, October 9, 2024  :Completed

**Comment by wbruninx** [comment]
Template is not launching hence opening it manually and finally : 

![image](https://github.com/user-attachments/assets/ecc98d32-cabf-4eb7-88c7-3ec4df6fb9c2)

**Comment by marclelijveld** [comment]
Hi @wbruninx 
I'm running W11 myself for over a year and runs smoothly on my end. Did you actually run the installer? Or copied all the items manually? The fact the items are not in the right locations makes me assume you only downloaded the tool without installing. 

--Marc

**Comment by marclelijveld** [comment]
Also, if you run the installer as admin, not on your own account - this can cause the issue. The shared resources folder are unique for every user account. Therefore the files may be available in your admin account. Please check that as well.

--Marc

**Comment by wbruninx** [comment]
Hi Marc, 

I was downloading version ModelDocumenter.Installer_v2.1.0.msi
Ran the msi installer as local administrator
Saw the installer GUI popping-up, clicking a few times the next button, and message received install was successfully done.
Program files were copied in the right place w/ the installer process e.g. C:\Program Files (x86)\Data-Marc\ModelDocumenter
All the rest was done manually as a work around.

/w

**Comment by marclelijveld** [comment]
Ok. I just ran the installer on a clean W11 VM on my end and all files (including the ones you did manually) were places in the right locations right away. I have no idea what went wrong on your end, other than it may have been installed for a different user instead of your account. 

But, if I understand well, it works now. Happy to hear that. Apologies for the inconvenience. 
--Marc

**Comment by wbruninx** [comment]
No prob. Thanks for looking into this, appreciated. Eventually as you said, everything works now. Probably the issue might be linked to some restrictions and/or the setup of our "corporate" windows 11 image installed on our laptops.
